#!/usr/bin/env bash
set -e
# On exit, print a message if the hook failed (non-zero exit) and preserve the exit code
trap 'ret=$?; if [ $ret -ne 0 ]; then echo "pre-commit hook failed (exit code $ret)"; fi; exit $ret' EXIT


echo "Running pre-commit hooks"

npx validate-branch-name -r '^(prod|stg|dev)$|^(feature|fix|hotfix)/.+$'

echo "Formatting tf files"
cd $(git rev-parse --show-toplevel)
terraform fmt -check -recursive || { terraform fmt -write=true -recursive  && echo "Files were not well-formatted. Formatted files. Aborting commit." && exit 1; } && echo "Files are well-formatted"



terraform validate

# GITHUB_OWNER=codelawcorp-test terraform test

gitleaks git --staged

