module "this" {
  # Swap sources. These docs are autogenerated from actual terraform tests.
  source = "codelawcorp/repository/github"
  # source = "../../"
  # version = "~> 2.0.0"  # It is always recommended to pin the version

  name        = "repo-as-a-code"
  description = "This repository manages itself as code. Also it will manage other repositories in the future."

  archive_on_destroy = false

  bootstrap_tf_cloud = {
    tf_cloud_organization = "magzim21" # This is example. Replace with your organization name.
    tf_cloud_workspace    = "github"   # This is example. Replace with your workspace name.
    terraform_version     = try(file("${abspath(path.root)}/.terraform-version"), "latest")
    tfe_token             = var.tfe_token
    github_token          = var.github_token
  }
}

variable "tfe_token" {
  description = "Terraform Cloud token"
  type        = string
  sensitive   = true
  # default = null # uncomment after the first apply
  nullable = true
}
variable "github_token" {
  description = "GitHub token"
  type        = string
  sensitive   = true
  # default = null # uncomment after the first apply
  nullable = true
}

