module "gh_repository" {

  # Swap sources. These docs are autogenerated.
  source  = "codelawcorp/repository/github"
  version = "4.3.1"
  # version = "~> 2.0.0" # It is always recommended to pin version

  name        = try(var.name, null)
  description = try(var.description, null)
  visibility  = try(var.visibility, null)

  homepage_url = try(var.homepage_url, "https://${var.pages.cname}", var.pages != null ? "https://${local.domain_name}" : null, null) # Seems like Vercel overwrites this.
  fork         = try(var.fork, null)
  source_owner = try(var.source_owner, null)
  source_repo  = try(var.source_repo, null)


  archived    = try(var.archived, null)
  is_template = try(var.is_template, null)

  # topics       = try(var.topics, [])
  topics = try(var.topics, [])

  has_projects    = try(var.has_projects, null)
  has_wiki        = try(var.has_wiki, null)
  has_discussions = try(var.has_discussions, null)

  # Merge settings
  allow_auto_merge       = try(var.allow_auto_merge, null)
  allow_merge_commit     = try(var.allow_merge_commit, null)
  allow_squash_merge     = try(var.allow_squash_merge, null)
  allow_rebase_merge     = try(var.allow_rebase_merge, null)
  delete_branch_on_merge = try(var.delete_branch_on_merge, null)

  merge_commit_title          = try(var.merge_commit_title, null)
  merge_commit_message        = try(var.merge_commit_message, null)
  squash_merge_commit_title   = try(var.squash_merge_commit_title, null)
  squash_merge_commit_message = try(var.squash_merge_commit_message, null)




  # Template configuration (if using a template repository)
  template = try(var.template, null)


  default_branch    = var.default_branch
  branches          = try(var.branches, null)
  custom_properties = []



  deploy_keys = []

  #   # GitHub Pages configuration (optional)
  pages = try(var.pages, null) != null ? {
    build_type = try(var.pages.build_type, "workflow")
    cname      = try(var.pages.cname, local.domain_name, null)
    # source = try(var.pages.source, null)
    source = try(var.pages.source, null) != null ? {
      branch = try(var.pages.source.branch, "gh-pages")
      path   = try(var.pages.source.path, "/")
    } : null
  } : null

  environments = try(var.environments, null)

  actions_variables = try(var.actions_variables, null)

  actions_secrets = try(var.actions_secrets, null)

  # This also automatically enables vulnerability_alerts
  # vulnerability_alerts               = true
  # enable_dependabot_security_updates = try(var.enable_dependabot_security_updates, true, null)


  # Configure webhooks for the repository
  webhooks = try(var.webhooks, null)





  users = try(var.users, null)

  teams = try(var.teams, null)

  # Add GitHub repository files
  repository_files = (
    try(var.archived, false)
    ? {}
    : merge(
      try(var.pages, null) != null && !try(var.pages.do_not_create_index_html, false) ? {
        "index.html" = {
          content = templatefile(
            "${path.module}/templates/index.html.tpl",
            {
              title   = try(var.name, "Repository")
              heading = try(var.name, "Repository")
              lede    = "This repository is managed with Terraform. Review the README for project details."
              #   lede = try(
              #     trimspace(var.description) != "" ? trimspace(var.description) : local.index_html_default_body,
              #     local.index_html_default_body
              #   )
            }
          )
          overwrite_on_create = true
        }
      } : {},
      try(var.repository_files, {})
    )
  )

  # Add issue labels
  issue_labels = try(var.issue_labels, [])

  # Create an autolink reference
  autolink_references = [
  ]

  # gitignore_template = "Python"
  # license_template   = "mit"

  # actions_repository_permissions = {
  #   allowed_actions = "selected"
  #   enabled         = true
  #   allowed_actions_config = {
  #     github_owned_allowed = true
  #     patterns_allowed     = ["actions/*"]
  #     verified_allowed     = true
  #   }
  # }

  # Projects are not supported by this module.
  # 410 Projects (classic) has been deprecated in favor of the new Projects experience. []

  archive_on_destroy = try(var.archive_on_destroy, null)
}


